import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import businessesRouter from "./businesses";
import statsRouter from "./stats";
import reviewsRouter from "./reviews";
import messagesRouter from "./messages";
import ordersRouter from "./orders";
import analyticsRouter from "./analytics";
import dashboardRouter from "./dashboard";
import productsRouter from "./products";
import favoritesRouter from "./favorites";
import notificationsRouter from "./notifications";
import settingsRouter from "./settings";
import adminUsersRouter from "./admin-users";
import adminActivityRouter from "./admin-activity";
import servicesRouter from "./services";
import collectionsRouter from "./collections";
import uploadRouter from "./upload";
import supportRouter from "./support";
import ridersRouter from "./riders";
import deliveriesRouter from "./deliveries";
import paymentsRouter from "./payments";
import disputesRouter from "./disputes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(businessesRouter);
router.use(statsRouter);
router.use(reviewsRouter);
router.use(messagesRouter);
router.use(ordersRouter);
router.use(analyticsRouter);
router.use(dashboardRouter);
router.use(productsRouter);
router.use(favoritesRouter);
router.use(notificationsRouter);
router.use(settingsRouter);
router.use(adminUsersRouter);
router.use(adminActivityRouter);
router.use(servicesRouter);
router.use(collectionsRouter);
router.use(uploadRouter);
router.use(supportRouter);
router.use(ridersRouter);
router.use(deliveriesRouter);
router.use(paymentsRouter);
router.use(disputesRouter);

export default router;
