import { Router, type IRouter } from "express";
import healthRouter from "../features/health/health.routes";
import authRouter from "../features/auth/auth.routes";
import businessesRouter from "../features/businesses/businesses.routes";
import statsRouter from "./stats";
import reviewsRouter from "./reviews";
import messagesRouter from "./messages";
import ordersRouter from "./orders";
import analyticsRouter from "./analytics";
import dashboardRouter from "./dashboard";
import productsRouter from "../features/products/products.routes";
import favoritesRouter from "./favorites";
import notificationsRouter from "./notifications";
import settingsRouter from "./settings";
import adminUsersRouter from "./admin-users";
import adminActivityRouter from "./admin-activity";
import servicesRouter from "./services";
import collectionsRouter from "../features/collections/collections.routes";
import uploadRouter from "./upload";
import supportRouter from "./support";
import ridersRouter from "./riders";
import deliveriesRouter from "./deliveries";
import paymentsRouter from "./payments";
import disputesRouter from "./disputes";
import tradeRouter from "./trade";
import tradeOrdersRouter from "./trade-orders";
import tradeMessagesRouter from "./trade-messages";
import boostsRouter from "./boosts";
import flashSalesRouter from "./flash-sales";
import adminModerationRouter from "./admin-moderation";
import newsletterRouter from "./newsletter";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(businessesRouter);
router.use(statsRouter);
router.use(reviewsRouter);
router.use(messagesRouter);
router.use(ordersRouter);
router.use(analyticsRouter);
router.use(dashboardRouter);
router.use(productsRouter);
router.use(favoritesRouter);
router.use(notificationsRouter);
router.use(settingsRouter);
router.use(adminUsersRouter);
router.use(adminActivityRouter);
router.use(servicesRouter);
router.use(collectionsRouter);
router.use(uploadRouter);
router.use(supportRouter);
router.use(ridersRouter);
router.use(deliveriesRouter);
router.use(paymentsRouter);
router.use(disputesRouter);
router.use(tradeRouter);
router.use(tradeOrdersRouter);
router.use(tradeMessagesRouter);
router.use(boostsRouter);
router.use(flashSalesRouter);
router.use(adminModerationRouter);
router.use(newsletterRouter);

export default router;
